-- AlterTable
ALTER TABLE `notifications` MODIFY COLUMN `type` ENUM('BOOKING_CONFIRMED', 'SESSION_REMINDER', 'SESSION_STARTING', 'SESSION_LIVE', 'SESSION_COMPLETED', 'SESSION_CANCELLED', 'NEW_REVIEW', 'ACHIEVEMENT_UNLOCKED', 'PAYMENT_SUCCESS', 'SEAT_AVAILABLE', 'QUIZ_LAUNCHED', 'CODING_QUESTION_LAUNCHED', 'RESOURCE_UPLOADED', 'SESSION_REQUEST_APPROVED', 'SESSION_REQUEST_REJECTED') NOT NULL;
